In [4]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [3]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
#for drop Nan Temprory

In [4]:
df.dropna()

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [ ]:
#for drop permanent

In [6]:
df.dropna(inplace = True)

In [7]:
df

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [8]:
df.dropna(axis=1)

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [10]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [11]:
df.dropna(axis = 1)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  SibSp  Parch  \
0                              Braund, Mr. Owen Harris    male      1      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                               Heikkinen, Miss. Laina  female      0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
4                             Allen, Mr. William Henry    male      0      0   
..                                                 ...     ...    ...    ...   
886                              Montvila, Rev. Juozas    male      0      0   
887                       Graham, Miss. Margaret Edith  female      0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female      1      2   
889                              Behr, Mr. Karl Howell    male      0      0   
890                                Dooley, Mr. Patrick    male      0      0   

               Ticket     Fare  
0           A/5 21171   7.2500  
1            PC 17599  71.2833  
2    STON/O2. 3101282   7.9250  
3              113803  53.1000  
4              373450   8.0500  
..                ...      ...  
886            211536  13.0000  
887            112053  30.0000  
888        W./C. 6607  23.4500  
889            111369  30.0000  
890            370376   7.7500  

[891 rows x 9 columns]

In [13]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
df.dropna(axis = 1, how = 'all')

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [15]:
df.dropna(axis = 1,thresh =800)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  SibSp  Parch  \
0                              Braund, Mr. Owen Harris    male      1      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                               Heikkinen, Miss. Laina  female      0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
4                             Allen, Mr. William Henry    male      0      0   
..                                                 ...     ...    ...    ...   
886                              Montvila, Rev. Juozas    male      0      0   
887                       Graham, Miss. Margaret Edith  female      0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female      1      2   
889                              Behr, Mr. Karl Howell    male      0      0   
890                                Dooley, Mr. Patrick    male      0      0   

               Ticket     Fare Embarked  
0           A/5 21171   7.2500        S  
1            PC 17599  71.2833        C  
2    STON/O2. 3101282   7.9250        S  
3              113803  53.1000        S  
4              373450   8.0500        S  
..                ...      ...      ...  
886            211536  13.0000        S  
887            112053  30.0000        S  
888        W./C. 6607  23.4500        S  
889            111369  30.0000        C  
890            370376   7.7500        Q  

[891 rows x 10 columns]

In [16]:
df.dropna(axis = 1, how = 'all')

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [17]:
df.dropna(axis = 0, how = 'all')

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [18]:
df.fillna(value="sudh")

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  sudh      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500  sudh        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250  sudh        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500  sudh        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000  sudh        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500  sudh        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500  sudh        Q  

[891 rows x 12 columns]

In [19]:
df.fillna(value=df['Age'].mean())

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare      Cabin Embarked  
0        1      0         A/5 21171   7.2500  29.699118        S  
1        1      0          PC 17599  71.2833        C85        C  
2        0      0  STON/O2. 3101282   7.9250  29.699118        S  
3        1      0            113803  53.1000       C123        S  
4        0      0            373450   8.0500  29.699118        S  
..     ...    ...               ...      ...        ...      ...  
886      0      0            211536  13.0000  29.699118        S  
887      0      0            112053  30.0000        B42        S  
888      1      2        W./C. 6607  23.4500  29.699118        S  
889      0      0            111369  30.0000       C148        C  
890      0      0            370376   7.7500  29.699118        Q  

[891 rows x 12 columns]

In [20]:
df.groupby('Survived').describe()

PassengerId                                                     \
               count        mean         std  min     25%    50%    75%   
Survived                                                                  
0              549.0  447.016393  260.640469  1.0  211.00  455.0  675.0   
1              342.0  444.368421  252.358840  2.0  250.75  439.5  651.5   

                Pclass            ... Parch        Fare                        \
            max  count      mean  ...   75%  max  count       mean        std   
Survived                          ...                                           
0         891.0  549.0  2.531876  ...   0.0  6.0  549.0  22.117887  31.388207   
1         890.0  342.0  1.950292  ...   1.0  5.0  342.0  48.395408  66.596998   

                                              
          min      25%   50%   75%       max  
Survived                                      
0         0.0   7.8542  10.5  26.0  263.0000  
1         0.0  12.4750  26.0  57.0  512.3292  

[2 rows x 48 columns]

In [24]:
df.groupby('Survived').describe()['PassengerId']

count        mean         std  min     25%    50%    75%    max
Survived                                                                 
0         549.0  447.016393  260.640469  1.0  211.00  455.0  675.0  891.0
1         342.0  444.368421  252.358840  2.0  250.75  439.5  651.5  890.0

In [25]:
df.groupby('Survived').describe()['PassengerId'].transpose()

Survived           0           1
count     549.000000  342.000000
mean      447.016393  444.368421
std       260.640469  252.358840
min         1.000000    2.000000
25%       211.000000  250.750000
50%       455.000000  439.500000
75%       675.000000  651.500000
max       891.000000  890.000000

In [26]:
pd.read_csv('bank.csv' , sep=';')

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
0     cellular   19   oct        79         1     -1         0  unknown  no  
1     cellular   11   may       220         1    339         4  failure  no  
2     cellular   16   apr       185         1    330         1  failure  no  
3      unknown    3   jun       199         4     -1         0  unknown  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4517   unknown    9   may       153         1     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  
4520  cellular    3   apr       345         2    249         7    other  no  

[4521 rows x 17 columns]

In [27]:
df2 = pd.read_csv('bank.csv' , sep=';')

In [28]:
df2

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
0     cellular   19   oct        79         1     -1         0  unknown  no  
1     cellular   11   may       220         1    339         4  failure  no  
2     cellular   16   apr       185         1    330         1  failure  no  
3      unknown    3   jun       199         4     -1         0  unknown  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4517   unknown    9   may       153         1     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  
4520  cellular    3   apr       345         2    249         7    other  no  

[4521 rows x 17 columns]

In [29]:
df2.head()

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

In [32]:
l = []
for i in df2["education"].unique():
    l.append(df2[df2["education"]==i])

In [33]:
l

[      age            job   marital education default  balance housing loan  \
 0      30     unemployed   married   primary      no     1787      no   no   
 9      43       services   married   primary      no      -88     yes  yes   
 18     25    blue-collar    single   primary      no     -221     yes   no   
 26     55    blue-collar   married   primary      no      627     yes   no   
 36     78        retired  divorced   primary      no      229      no   no   
 ...   ...            ...       ...       ...     ...      ...     ...  ...   
 4480   23    blue-collar   married   primary      no     1158     yes   no   
 4485   53    blue-collar   married   primary      no      238     yes   no   
 4486   37    blue-collar   married   primary      no      378     yes   no   
 4499   45    blue-collar  divorced   primary      no      942      no   no   
 4503   60  self-employed   married   primary      no      362      no  yes   
 
         contact  day month  duration  campaign  p

In [34]:
l[0]

age            job   marital education default  balance housing loan  \
0      30     unemployed   married   primary      no     1787      no   no   
9      43       services   married   primary      no      -88     yes  yes   
18     25    blue-collar    single   primary      no     -221     yes   no   
26     55    blue-collar   married   primary      no      627     yes   no   
36     78        retired  divorced   primary      no      229      no   no   
...   ...            ...       ...       ...     ...      ...     ...  ...   
4480   23    blue-collar   married   primary      no     1158     yes   no   
4485   53    blue-collar   married   primary      no      238     yes   no   
4486   37    blue-collar   married   primary      no      378     yes   no   
4499   45    blue-collar  divorced   primary      no      942      no   no   
4503   60  self-employed   married   primary      no      362      no  yes   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
0      cellular   19   oct        79         1     -1         0  unknown   no  
9      cellular   17   apr       313         1    147         2  failure   no  
18      unknown   23   may       250         1     -1         0  unknown   no  
26      unknown    5   may       247         1     -1         0  unknown   no  
36    telephone   22   oct        97         1     -1         0  unknown  yes  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
4480   cellular   16   apr       743         1     -1         0  unknown   no  
4485   cellular   11   may       238         2    361         5  failure   no  
4486    unknown    9   may       514         1     -1         0  unknown   no  
4499   cellular   21   nov       362         1     -1         0  unknown   no  
4503   cellular   29   jul       816         6     -1         0  unknown  yes  

[678 rows x 17 columns]

In [36]:
df3 = l[0]

In [37]:
df3

age            job   marital education default  balance housing loan  \
0      30     unemployed   married   primary      no     1787      no   no   
9      43       services   married   primary      no      -88     yes  yes   
18     25    blue-collar    single   primary      no     -221     yes   no   
26     55    blue-collar   married   primary      no      627     yes   no   
36     78        retired  divorced   primary      no      229      no   no   
...   ...            ...       ...       ...     ...      ...     ...  ...   
4480   23    blue-collar   married   primary      no     1158     yes   no   
4485   53    blue-collar   married   primary      no      238     yes   no   
4486   37    blue-collar   married   primary      no      378     yes   no   
4499   45    blue-collar  divorced   primary      no      942      no   no   
4503   60  self-employed   married   primary      no      362      no  yes   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
0      cellular   19   oct        79         1     -1         0  unknown   no  
9      cellular   17   apr       313         1    147         2  failure   no  
18      unknown   23   may       250         1     -1         0  unknown   no  
26      unknown    5   may       247         1     -1         0  unknown   no  
36    telephone   22   oct        97         1     -1         0  unknown  yes  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
4480   cellular   16   apr       743         1     -1         0  unknown   no  
4485   cellular   11   may       238         2    361         5  failure   no  
4486    unknown    9   may       514         1     -1         0  unknown   no  
4499   cellular   21   nov       362         1     -1         0  unknown   no  
4503   cellular   29   jul       816         6     -1         0  unknown  yes  

[678 rows x 17 columns]

In [38]:
l[1]

age          job  marital  education default  balance housing loan  \
1      33     services  married  secondary      no     4789     yes  yes   
4      59  blue-collar  married  secondary      no        0     yes   no   
7      39   technician  married  secondary      no      147     yes   no   
10     39     services  married  secondary      no     9374     yes   no   
11     43       admin.  married  secondary      no      264     yes   no   
...   ...          ...      ...        ...     ...      ...     ...  ...   
4514   38  blue-collar  married  secondary      no     1205     yes   no   
4515   32     services   single  secondary      no      473     yes   no   
4516   33     services  married  secondary      no     -333     yes   no   
4518   57   technician  married  secondary      no      295      no   no   
4519   28  blue-collar  married  secondary      no     1137      no   no   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
1     cellular   11   may       220         1    339         4  failure  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
7     cellular    6   may       151         2     -1         0  unknown  no  
10     unknown   20   may       273         1     -1         0  unknown  no  
11    cellular   17   apr       113         2     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4514  cellular   20   apr        45         4    153         1  failure  no  
4515  cellular    7   jul       624         5     -1         0  unknown  no  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  

[2306 rows x 17 columns]

In [39]:
df4 = l[1]

In [40]:
df4

age          job  marital  education default  balance housing loan  \
1      33     services  married  secondary      no     4789     yes  yes   
4      59  blue-collar  married  secondary      no        0     yes   no   
7      39   technician  married  secondary      no      147     yes   no   
10     39     services  married  secondary      no     9374     yes   no   
11     43       admin.  married  secondary      no      264     yes   no   
...   ...          ...      ...        ...     ...      ...     ...  ...   
4514   38  blue-collar  married  secondary      no     1205     yes   no   
4515   32     services   single  secondary      no      473     yes   no   
4516   33     services  married  secondary      no     -333     yes   no   
4518   57   technician  married  secondary      no      295      no   no   
4519   28  blue-collar  married  secondary      no     1137      no   no   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
1     cellular   11   may       220         1    339         4  failure  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
7     cellular    6   may       151         2     -1         0  unknown  no  
10     unknown   20   may       273         1     -1         0  unknown  no  
11    cellular   17   apr       113         2     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4514  cellular   20   apr        45         4    153         1  failure  no  
4515  cellular    7   jul       624         5     -1         0  unknown  no  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  

[2306 rows x 17 columns]

In [42]:
pd.concat([df3,df4])

age          job   marital  education default  balance housing loan  \
0      30   unemployed   married    primary      no     1787      no   no   
9      43     services   married    primary      no      -88     yes  yes   
18     25  blue-collar    single    primary      no     -221     yes   no   
26     55  blue-collar   married    primary      no      627     yes   no   
36     78      retired  divorced    primary      no      229      no   no   
...   ...          ...       ...        ...     ...      ...     ...  ...   
4514   38  blue-collar   married  secondary      no     1205     yes   no   
4515   32     services    single  secondary      no      473     yes   no   
4516   33     services   married  secondary      no     -333     yes   no   
4518   57   technician   married  secondary      no      295      no   no   
4519   28  blue-collar   married  secondary      no     1137      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
0      cellular   19   oct        79         1     -1         0  unknown   no  
9      cellular   17   apr       313         1    147         2  failure   no  
18      unknown   23   may       250         1     -1         0  unknown   no  
26      unknown    5   may       247         1     -1         0  unknown   no  
36    telephone   22   oct        97         1     -1         0  unknown  yes  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
4514   cellular   20   apr        45         4    153         1  failure   no  
4515   cellular    7   jul       624         5     -1         0  unknown   no  
4516   cellular   30   jul       329         5     -1         0  unknown   no  
4518   cellular   19   aug       151        11     -1         0  unknown   no  
4519   cellular    6   feb       129         4    211         3    other   no  

[2984 rows x 17 columns]

In [46]:
d1 = df3.head()

In [45]:
d =df4.head()

In [47]:
pd.concat([d1,d])

age          job   marital  education default  balance housing loan  \
0    30   unemployed   married    primary      no     1787      no   no   
9    43     services   married    primary      no      -88     yes  yes   
18   25  blue-collar    single    primary      no     -221     yes   no   
26   55  blue-collar   married    primary      no      627     yes   no   
36   78      retired  divorced    primary      no      229      no   no   
1    33     services   married  secondary      no     4789     yes  yes   
4    59  blue-collar   married  secondary      no        0     yes   no   
7    39   technician   married  secondary      no      147     yes   no   
10   39     services   married  secondary      no     9374     yes   no   
11   43       admin.   married  secondary      no      264     yes   no   

      contact  day month  duration  campaign  pdays  previous poutcome    y  
0    cellular   19   oct        79         1     -1         0  unknown   no  
9    cellular   17   apr       313         1    147         2  failure   no  
18    unknown   23   may       250         1     -1         0  unknown   no  
26    unknown    5   may       247         1     -1         0  unknown   no  
36  telephone   22   oct        97         1     -1         0  unknown  yes  
1    cellular   11   may       220         1    339         4  failure   no  
4     unknown    5   may       226         1     -1         0  unknown   no  
7    cellular    6   may       151         2     -1         0  unknown   no  
10    unknown   20   may       273         1     -1         0  unknown   no  
11   cellular   17   apr       113         2     -1         0  unknown   no

In [48]:
pd.concat([d1,d],axis = 1)

age          job   marital education default  balance housing loan  \
0   30.0   unemployed   married   primary      no   1787.0      no   no   
1    NaN          NaN       NaN       NaN     NaN      NaN     NaN  NaN   
4    NaN          NaN       NaN       NaN     NaN      NaN     NaN  NaN   
7    NaN          NaN       NaN       NaN     NaN      NaN     NaN  NaN   
9   43.0     services   married   primary      no    -88.0     yes  yes   
10   NaN          NaN       NaN       NaN     NaN      NaN     NaN  NaN   
11   NaN          NaN       NaN       NaN     NaN      NaN     NaN  NaN   
18  25.0  blue-collar    single   primary      no   -221.0     yes   no   
26  55.0  blue-collar   married   primary      no    627.0     yes   no   
36  78.0      retired  divorced   primary      no    229.0      no   no   

      contact   day  ... loan   contact   day  month  duration campaign  \
0    cellular  19.0  ...  NaN       NaN   NaN    NaN       NaN      NaN   
1         NaN   NaN  ...  yes  cellular  11.0    may     220.0      1.0   
4         NaN   NaN  ...   no   unknown   5.0    may     226.0      1.0   
7         NaN   NaN  ...   no  cellular   6.0    may     151.0      2.0   
9    cellular  17.0  ...  NaN       NaN   NaN    NaN       NaN      NaN   
10        NaN   NaN  ...   no   unknown  20.0    may     273.0      1.0   
11        NaN   NaN  ...   no  cellular  17.0    apr     113.0      2.0   
18    unknown  23.0  ...  NaN       NaN   NaN    NaN       NaN      NaN   
26    unknown   5.0  ...  NaN       NaN   NaN    NaN       NaN      NaN   
36  telephone  22.0  ...  NaN       NaN   NaN    NaN       NaN      NaN   

    pdays  previous poutcome    y  
0     NaN       NaN      NaN  NaN  
1   339.0       4.0  failure   no  
4    -1.0       0.0  unknown   no  
7    -1.0       0.0  unknown   no  
9     NaN       NaN      NaN  NaN  
10   -1.0       0.0  unknown   no  
11   -1.0       0.0  unknown   no  
18    NaN       NaN      NaN  NaN  
26    NaN       NaN      NaN  NaN  
36    NaN       NaN      NaN  NaN  

[10 rows x 34 columns]

In [50]:
df3.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [51]:
df3 = df3.head()[['age', 'job', 'marital']]

In [52]:
df3

age          job   marital
0    30   unemployed   married
9    43     services   married
18   25  blue-collar    single
26   55  blue-collar   married
36   78      retired  divorced

In [53]:
df4.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [54]:
df4 = df4.head()[['age', 'job', 'marital']]

In [55]:
df4

age          job  marital
1    33     services  married
4    59  blue-collar  married
7    39   technician  married
10   39     services  married
11   43       admin.  married

In [56]:
pd.concat([df3,df4],axis = 1)

age          job   marital   age          job  marital
0   30.0   unemployed   married   NaN          NaN      NaN
1    NaN          NaN       NaN  33.0     services  married
4    NaN          NaN       NaN  59.0  blue-collar  married
7    NaN          NaN       NaN  39.0   technician  married
9   43.0     services   married   NaN          NaN      NaN
10   NaN          NaN       NaN  39.0     services  married
11   NaN          NaN       NaN  43.0       admin.  married
18  25.0  blue-collar    single   NaN          NaN      NaN
26  55.0  blue-collar   married   NaN          NaN      NaN
36  78.0      retired  divorced   NaN          NaN      NaN

In [59]:
df3.loc[[9,18],['job','marital']]

job  marital
9      services  married
18  blue-collar   single

In [60]:
df3.iloc[[1,2],[1,2]]

job  marital
9      services  married
18  blue-collar   single

In [61]:
df3

age          job   marital
0    30   unemployed   married
9    43     services   married
18   25  blue-collar    single
26   55  blue-collar   married
36   78      retired  divorced

In [62]:
df4

age          job  marital
1    33     services  married
4    59  blue-collar  married
7    39   technician  married
10   39     services  married
11   43       admin.  married

In [65]:
pd.merge(df3,df4)

Empty DataFrame
Columns: [age, job, marital]
Index: []

In [66]:
pd.merge(df3,df4,on = 'age')

age     job_x marital_x   job_y marital_y
0   43  services   married  admin.   married

In [67]:
pd.merge(df3,df4,on = 'age',how = 'left')

age        job_x marital_x   job_y marital_y
0   30   unemployed   married     NaN       NaN
1   43     services   married  admin.   married
2   25  blue-collar    single     NaN       NaN
3   55  blue-collar   married     NaN       NaN
4   78      retired  divorced     NaN       NaN

In [71]:
pd.merge(df3,df4,on = 'age',how = 'right')

age     job_x marital_x        job_y marital_y
0   33       NaN       NaN     services   married
1   59       NaN       NaN  blue-collar   married
2   39       NaN       NaN   technician   married
3   39       NaN       NaN     services   married
4   43  services   married       admin.   married

In [72]:
pd.merge(df3,df4,on = 'age',how = 'outer')

age        job_x marital_x        job_y marital_y
0   30   unemployed   married          NaN       NaN
1   43     services   married       admin.   married
2   25  blue-collar    single          NaN       NaN
3   55  blue-collar   married          NaN       NaN
4   78      retired  divorced          NaN       NaN
5   33          NaN       NaN     services   married
6   59          NaN       NaN  blue-collar   married
7   39          NaN       NaN   technician   married
8   39          NaN       NaN     services   married

In [73]:
df3

age          job   marital
0    30   unemployed   married
9    43     services   married
18   25  blue-collar    single
26   55  blue-collar   married
36   78      retired  divorced

In [74]:
df4

age          job  marital
1    33     services  married
4    59  blue-collar  married
7    39   technician  married
10   39     services  married
11   43       admin.  married

In [1]:
import pandas as pd

In [17]:
pd.DataFrame({'col1' :[1,2,3,4,5],
              'col2' :[45,58,78,55,65],
              'col3' :"sudhir kumar dev shourya "
})

col1  col2                       col3
0     1    45  sudhir kumar dev shourya 
1     2    58  sudhir kumar dev shourya 
2     3    78  sudhir kumar dev shourya 
3     4    55  sudhir kumar dev shourya 
4     5    65  sudhir kumar dev shourya

In [16]:
"sudhir kumar dev shourya dfcr ".split()

['sudhir', 'kumar', 'dev', 'shourya', 'dfcr']

In [18]:
df = pd.DataFrame({'col1' :[1,2,3,4,5],
              'col2' :[45,58,78,55,65],
              'col3' :"sudhir kumar dev shourya "
})

In [19]:
df

col1  col2                       col3
0     1    45  sudhir kumar dev shourya 
1     2    58  sudhir kumar dev shourya 
2     3    78  sudhir kumar dev shourya 
3     4    55  sudhir kumar dev shourya 
4     5    65  sudhir kumar dev shourya

In [20]:
df['col4']=1

In [21]:
df

col1  col2                       col3  col4
0     1    45  sudhir kumar dev shourya      1
1     2    58  sudhir kumar dev shourya      1
2     3    78  sudhir kumar dev shourya      1
3     4    55  sudhir kumar dev shourya      1
4     5    65  sudhir kumar dev shourya      1

In [22]:
df['col4']=df['col1']**2

In [23]:
df

col1  col2                       col3  col4
0     1    45  sudhir kumar dev shourya      1
1     2    58  sudhir kumar dev shourya      4
2     3    78  sudhir kumar dev shourya      9
3     4    55  sudhir kumar dev shourya     16
4     5    65  sudhir kumar dev shourya     25

In [24]:
df['col5'] = df['col3'].str[0]

In [25]:
df

col1  col2                       col3  col4 col5
0     1    45  sudhir kumar dev shourya      1    s
1     2    58  sudhir kumar dev shourya      4    s
2     3    78  sudhir kumar dev shourya      9    s
3     4    55  sudhir kumar dev shourya     16    s
4     5    65  sudhir kumar dev shourya     25    s

In [28]:
pd.DataFrame({'col1' :[1,2,3,4,5],
              'col2' :[45,58,78,55,65],
              'col3' :"sudhir kumar dev shourya raja ".split()
})

col1  col2     col3
0     1    45   sudhir
1     2    58    kumar
2     3    78      dev
3     4    55  shourya
4     5    65     raja

In [27]:
"sudhir kumar dev shourya raja ".split()

['sudhir', 'kumar', 'dev', 'shourya', 'raja']

In [29]:
df = pd.DataFrame({'col1' :[1,2,3,4,5],
              'col2' :[45,58,78,55,65],
              'col3' :"sudhir kumar dev shourya raja ".split()
})

In [30]:
df

col1  col2     col3
0     1    45   sudhir
1     2    58    kumar
2     3    78      dev
3     4    55  shourya
4     5    65     raja

In [31]:
df['col4']=1

In [32]:
df

col1  col2     col3  col4
0     1    45   sudhir     1
1     2    58    kumar     1
2     3    78      dev     1
3     4    55  shourya     1
4     5    65     raja     1

In [33]:
df['col4']=df['col1']**2

In [34]:
df

col1  col2     col3  col4
0     1    45   sudhir     1
1     2    58    kumar     4
2     3    78      dev     9
3     4    55  shourya    16
4     5    65     raja    25

In [35]:
df['col5'] = df['col3'].str[0]

In [36]:
df

col1  col2     col3  col4 col5
0     1    45   sudhir     1    s
1     2    58    kumar     4    k
2     3    78      dev     9    d
3     4    55  shourya    16    s
4     5    65     raja    25    r

In [37]:
def test(a):
    return a**2

In [38]:
df['col4_4'] = df['col1'].apply(test)

In [39]:
df

col1  col2     col3  col4 col5  col4_4
0     1    45   sudhir     1    s       1
1     2    58    kumar     4    k       4
2     3    78      dev     9    d       9
3     4    55  shourya    16    s      16
4     5    65     raja    25    r      25

In [42]:
def test1(a):
    if a =='s':
        return 's'
    else:
        return 'z'

In [43]:
df['col6'] = df['col5'].apply(test1)

In [44]:
df

col1  col2     col3  col4 col5  col4_4 col6
0     1    45   sudhir     1    s       1    s
1     2    58    kumar     4    k       4    z
2     3    78      dev     9    d       9    z
3     4    55  shourya    16    s      16    s
4     5    65     raja    25    r      25    z

In [45]:
df['col6_6'] = df['col5'].apply(lambda a  : 's' if a == 's' else 'z')

In [46]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6
0     1    45   sudhir     1    s       1    s      s
1     2    58    kumar     4    k       4    z      z
2     3    78      dev     9    d       9    z      z
3     4    55  shourya    16    s      16    s      s
4     5    65     raja    25    r      25    z      z

In [47]:
df['col7'] = df['col3'].apply(len)

In [48]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6  col7
0     1    45   sudhir     1    s       1    s      s     6
1     2    58    kumar     4    k       4    z      z     5
2     3    78      dev     9    d       9    z      z     3
3     4    55  shourya    16    s      16    s      s     7
4     5    65     raja    25    r      25    z      z     4

In [49]:
import math

In [50]:
df['col8'] = df['col2'].apply(math.log)

In [51]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    45   sudhir     1    s       1    s      s     6  3.806662
1     2    58    kumar     4    k       4    z      z     5  4.060443
2     3    78      dev     9    d       9    z      z     3  4.356709
3     4    55  shourya    16    s      16    s      s     7  4.007333
4     5    65     raja    25    r      25    z      z     4  4.174387

In [53]:
import numpy as np

In [54]:
l = ["sudh",1,2,3,4]

In [55]:
type(l)

list

In [56]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [57]:
type(np.array(l))

numpy.ndarray

In [59]:
np.array([3,4,5,6,3,4.0])

array([3., 4., 5., 6., 3., 4.])

In [61]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [62]:
a = np.array([[1,2],[3,4]])

In [63]:
a

array([[1, 2],
       [3, 4]])

In [64]:
a[1]

array([3, 4])

In [65]:
a[1][1]

4

In [67]:
a1 = np.array([3,4,5,6,3,4.0])

In [68]:
a1

array([3., 4., 5., 6., 3., 4.])

In [69]:
a1[1]

4.0

In [70]:
np.array([1,2,3,4],ndmin =4)

array([[[[1, 2, 3, 4]]]])

In [71]:
a2 = np.array([1,2,3,4],ndmin =4)

In [72]:
a2

array([[[[1, 2, 3, 4]]]])

In [73]:
a2[0]

array([[[1, 2, 3, 4]]])

In [74]:
a2[0][0]

array([[1, 2, 3, 4]])

In [75]:
a2[0][0][0]

array([1, 2, 3, 4])

In [76]:
a2[0][0][0][0]

1

In [77]:
a

array([[1, 2],
       [3, 4]])

In [78]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [79]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [80]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [82]:
b = [1,2,3,4,5]
np.asarray(b)

array([1, 2, 3, 4, 5])

In [84]:
np.asanyarray(np.mat(b))

matrix([[1, 2, 3, 4, 5]])

In [86]:
np.fromfunction(lambda i,j:i ==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [3]:
np.fromfunction(lambda i,j : i*j ,(4,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [4]:
np.mat(np.fromfunction(lambda i,j : i*j ,(4,4),dtype = int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [5]:
np.fromfunction(lambda i,j,z : i*j*z ,(3,3,2),dtype = int) 

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [6]:
np.fromfunction(lambda i,j,z : i*j*z ,(4,3,2),dtype = int) 

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [7]:
np.fromfunction(lambda i,j,z,p : i*j*z*p ,(4,3,2,2),dtype = int) 

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [8]:
np.fromfunction(lambda i,j,z : i*j*z ,(4,3,2),dtype = int) 

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [12]:
a = np.fromfunction(lambda i,j,z : i*j*z ,(4,3,2),dtype = int) 

In [13]:
a.ndim

3

In [14]:
a.size

24

In [15]:
a.shape

(4, 3, 2)

In [16]:
a.dtype

dtype('int32')

In [17]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [18]:
 a = np.fromfunction(lambda i,j : i*j ,(4,3),dtype = int) 

In [19]:
a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [20]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [23]:
 a = np.fromfunction(lambda i,j : i*j ,(400,100),dtype = int) 

In [24]:
a

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [22]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [25]:
np.random.rand(100,4)

array([[0.24831917, 0.92414064, 0.4219324 , 0.05428571],
       [0.35309674, 0.95161093, 0.92557438, 0.33302473],
       [0.12186255, 0.50342978, 0.02808118, 0.86947824],
       [0.76922276, 0.1079001 , 0.11565076, 0.75697391],
       [0.40474472, 0.36044228, 0.56837458, 0.12846899],
       [0.72599999, 0.68493868, 0.51397916, 0.61981504],
       [0.80303418, 0.22809139, 0.18981478, 0.05674517],
       [0.17174975, 0.05432009, 0.6094586 , 0.53693902],
       [0.06661957, 0.67143642, 0.51920028, 0.82037625],
       [0.15897846, 0.30367675, 0.20270521, 0.00874035],
       [0.3009179 , 0.08149353, 0.33390365, 0.83986703],
       [0.20819659, 0.28893065, 0.39266184, 0.37149071],
       [0.17149587, 0.07024725, 0.47293683, 0.26442649],
       [0.96424895, 0.59881422, 0.24369591, 0.27385933],
       [0.60229518, 0.77339895, 0.2098879 , 0.17079958],
       [0.56730962, 0.72602358, 0.02919507, 0.15138576],
       [0.21130461, 0.70173718, 0.0253429 , 0.94455385],
       [0.8677512 , 0.23582455,

In [28]:
np.random.randint(4,50)

45

In [30]:
np.random.randn(4,50)

array([[ 1.42416082, -0.15036795,  0.15651624, -1.52202291, -0.62229656,
         1.02618317,  0.31777913,  0.86315983, -0.0298767 ,  0.58366333,
         0.55474321, -1.18495089,  0.52717119,  0.07427648, -0.81919776,
         0.02948048, -0.19569884, -0.00760476,  0.22627914,  0.35138541,
        -1.18835005, -0.97060551,  0.12220087, -0.84093871,  0.38816119,
         1.62197377, -0.23829814,  0.33444857,  0.8733792 ,  0.67560096,
         0.51836391,  3.01860195,  0.73990289, -0.06027677, -0.20553733,
        -1.85891534, -1.64502969,  0.62915737,  0.16529983,  0.51155483,
        -1.07517797, -1.54907511,  0.43070056, -0.92019999, -0.72834004,
        -0.17533366, -0.34978534, -1.79338403,  0.57982509,  2.20853592],
       [-0.08661975, -0.87882865, -0.9452214 ,  0.12266873,  0.84580206,
         0.58960902,  2.73596272,  1.55543348, -0.21707937, -2.23741644,
        -0.48844432,  0.70032309,  0.17266146, -0.08823023, -0.45251113,
        -0.8210739 , -0.43078362, -1.61895553, -0.

In [31]:
b = np.random.randn(4,50)

In [32]:
pd.DataFrame(b)

0         1         2         3         4         5         6   \
0 -0.109312  1.200654 -0.569382 -1.096752  0.692682 -0.076074  0.683828   
1  1.235439 -0.990007 -1.745801  0.320145  0.600365 -0.999736 -0.783991   
2 -0.786497  0.983044  1.011373 -0.840709  0.034688 -1.196182 -0.213984   
3 -0.912247 -0.753523  1.038556 -0.502269 -0.614715  0.397766  0.463101   

         7         8         9   ...        40        41        42        43  \
0  0.018731  1.369971  1.208853  ...  1.392997  0.968361  0.481449  0.199032   
1  1.644244 -0.297166 -0.439385  ... -1.207892  0.687774  1.622080 -0.304084   
2 -1.227343  1.262657  0.525827  ... -0.978784 -2.339917 -1.173991 -0.815651   
3 -0.536044  2.764866 -0.523204  ... -0.445328 -1.326769 -2.536823 -0.903908   

         44        45        46        47        48        49  
0 -1.432635 -0.498919  1.388843  0.646395 -0.973521  0.436984  
1 -0.199820  0.715014 -0.877782  0.832097  0.925483 -0.519927  
2 -0.697841  1.062145  0.993014 -0.460317  0.981980 -0.365254  
3 -0.071196 -0.305819 -0.048599 -1.072608 -0.689230 -2.111980  

[4 rows x 50 columns]

In [33]:
a = np.fromfunction(lambda i,j,z : i*j*z ,(4,3,2),dtype = int) 

In [35]:
a.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [36]:
z = a.reshape(12,2)

In [37]:
pd.DataFrame(z)

0  1
0   0  0
1   0  0
2   0  0
3   0  0
4   0  1
5   0  2
6   0  0
7   0  2
8   0  4
9   0  0
10  0  3
11  0  6

In [39]:
np.arange(4,10.5,.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [40]:
a1 = np.arange(4,10.5,.2)

In [41]:
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [42]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [43]:
arr = np.random.rand(4,5)

In [44]:
arr

array([[0.08267376, 0.09818958, 0.51240588, 0.19998882, 0.19208235],
       [0.53716946, 0.49964579, 0.3342675 , 0.97790662, 0.66840686],
       [0.68990502, 0.64141393, 0.78852927, 0.05840055, 0.64873992],
       [0.47824622, 0.26136685, 0.5491013 , 0.412116  , 0.6223673 ]])

In [45]:
arr > 0.5

array([[False, False,  True, False, False],
       [ True, False, False,  True,  True],
       [ True,  True,  True, False,  True],
       [False, False,  True, False,  True]])

In [46]:
arr[arr > 0.5]

array([0.51240588, 0.53716946, 0.97790662, 0.66840686, 0.68990502,
       0.64141393, 0.78852927, 0.64873992, 0.5491013 , 0.6223673 ])

In [47]:
arr

array([[0.08267376, 0.09818958, 0.51240588, 0.19998882, 0.19208235],
       [0.53716946, 0.49964579, 0.3342675 , 0.97790662, 0.66840686],
       [0.68990502, 0.64141393, 0.78852927, 0.05840055, 0.64873992],
       [0.47824622, 0.26136685, 0.5491013 , 0.412116  , 0.6223673 ]])

In [48]:
arr[[1,2],[2]]

array([0.3342675 , 0.78852927])

In [49]:
arr = np.random.rand(8,5)

In [50]:
arr

array([[0.09430637, 0.85038139, 0.46827837, 0.07833117, 0.37872635],
       [0.52805317, 0.77515504, 0.77734295, 0.42458604, 0.72304549],
       [0.52471309, 0.46863583, 0.91996273, 0.78431745, 0.76922141],
       [0.3531562 , 0.24505605, 0.94418146, 0.25965821, 0.183062  ],
       [0.49470392, 0.08755811, 0.8401234 , 0.83621358, 0.60848087],
       [0.29719416, 0.01381638, 0.15783608, 0.7829178 , 0.70994087],
       [0.98219734, 0.15204191, 0.99759796, 0.09873939, 0.32809293],
       [0.88471466, 0.15360391, 0.38772787, 0.88711267, 0.18388258]])

In [55]:
a2 = arr[1:8 , 0:3]

In [56]:
a2

array([[0.52805317, 0.77515504, 0.77734295],
       [0.52471309, 0.46863583, 0.91996273],
       [0.3531562 , 0.24505605, 0.94418146],
       [0.49470392, 0.08755811, 0.8401234 ],
       [0.29719416, 0.01381638, 0.15783608],
       [0.98219734, 0.15204191, 0.99759796],
       [0.88471466, 0.15360391, 0.38772787]])

In [57]:
a2[0][0] = 100

In [58]:
a2

array([[1.00000000e+02, 7.75155040e-01, 7.77342949e-01],
       [5.24713091e-01, 4.68635834e-01, 9.19962732e-01],
       [3.53156203e-01, 2.45056053e-01, 9.44181460e-01],
       [4.94703921e-01, 8.75581095e-02, 8.40123404e-01],
       [2.97194156e-01, 1.38163813e-02, 1.57836076e-01],
       [9.82197336e-01, 1.52041906e-01, 9.97597958e-01],
       [8.84714664e-01, 1.53603907e-01, 3.87727869e-01]])

In [61]:
a = np.array([[1,2] , [3,4]])
b = np.array([[2,3] , [4,5]])

In [62]:
a

array([[1, 2],
       [3, 4]])

In [63]:
b

array([[2, 3],
       [4, 5]])

In [64]:
a*b

array([[ 2,  6],
       [12, 20]])

In [65]:
a@b

array([[10, 13],
       [22, 29]])

In [66]:
m = a@b

In [67]:
m

array([[10, 13],
       [22, 29]])

In [68]:
m/0

C:\Users\ADMIN-~1\AppData\Local\Temp/ipykernel_11448/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [5]:
l = [1,2,3,4,54]

In [6]:
np.asarray(l)

array([ 1,  2,  3,  4, 54])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros(((3,4,5)))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
np.ones(((3,6,2)))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [22]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [23]:
np.empty((4,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061074e-306, 2.33640395e-307],
       [7.56587584e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 2.78149851e-307,
        1.06811422e-306, 8.45590539e-307],
       [6.23054972e-307, 9.34609790e-307, 1.78019354e-306,
        1.69119330e-306, 1.24611470e-306]])

In [25]:
np.empty(((4,5,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [26]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [27]:
np.linspace(2,6,100)

array([2.        , 2.04040404, 2.08080808, 2.12121212, 2.16161616,
       2.2020202 , 2.24242424, 2.28282828, 2.32323232, 2.36363636,
       2.4040404 , 2.44444444, 2.48484848, 2.52525253, 2.56565657,
       2.60606061, 2.64646465, 2.68686869, 2.72727273, 2.76767677,
       2.80808081, 2.84848485, 2.88888889, 2.92929293, 2.96969697,
       3.01010101, 3.05050505, 3.09090909, 3.13131313, 3.17171717,
       3.21212121, 3.25252525, 3.29292929, 3.33333333, 3.37373737,
       3.41414141, 3.45454545, 3.49494949, 3.53535354, 3.57575758,
       3.61616162, 3.65656566, 3.6969697 , 3.73737374, 3.77777778,
       3.81818182, 3.85858586, 3.8989899 , 3.93939394, 3.97979798,
       4.02020202, 4.06060606, 4.1010101 , 4.14141414, 4.18181818,
       4.22222222, 4.26262626, 4.3030303 , 4.34343434, 4.38383838,
       4.42424242, 4.46464646, 4.50505051, 4.54545455, 4.58585859,
       4.62626263, 4.66666667, 4.70707071, 4.74747475, 4.78787879,
       4.82828283, 4.86868687, 4.90909091, 4.94949495, 4.98989

In [28]:
np.linspace(2,6,1000)

array([2.        , 2.004004  , 2.00800801, 2.01201201, 2.01601602,
       2.02002002, 2.02402402, 2.02802803, 2.03203203, 2.03603604,
       2.04004004, 2.04404404, 2.04804805, 2.05205205, 2.05605606,
       2.06006006, 2.06406406, 2.06806807, 2.07207207, 2.07607608,
       2.08008008, 2.08408408, 2.08808809, 2.09209209, 2.0960961 ,
       2.1001001 , 2.1041041 , 2.10810811, 2.11211211, 2.11611612,
       2.12012012, 2.12412412, 2.12812813, 2.13213213, 2.13613614,
       2.14014014, 2.14414414, 2.14814815, 2.15215215, 2.15615616,
       2.16016016, 2.16416416, 2.16816817, 2.17217217, 2.17617618,
       2.18018018, 2.18418418, 2.18818819, 2.19219219, 2.1961962 ,
       2.2002002 , 2.2042042 , 2.20820821, 2.21221221, 2.21621622,
       2.22022022, 2.22422422, 2.22822823, 2.23223223, 2.23623624,
       2.24024024, 2.24424424, 2.24824825, 2.25225225, 2.25625626,
       2.26026026, 2.26426426, 2.26826827, 2.27227227, 2.27627628,
       2.28028028, 2.28428428, 2.28828829, 2.29229229, 2.29629

In [32]:
np.linspace(2,6,10,endpoint = False, retstep = True)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [ ]:
np.linspace(2,6,10).reshape(5,2)

In [33]:
np.logspace(2,4,10, base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [35]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
a = np.arange(16).reshape(4,4)

In [39]:
a = np.arange(16).reshape(4,4)

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
a.max()

15

In [43]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
np.arange(4,40) 

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39])

In [53]:
np.arange(4,40).reshape(6,6)

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [54]:
a1 =np.arange(4,40).reshape(6,6)

In [55]:
a1

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [56]:
a1.max()

39

In [58]:
a1.max(axis = 0)

array([34, 35, 36, 37, 38, 39])

In [59]:
a1.max(axis = 1)

array([ 9, 15, 21, 27, 33, 39])

In [60]:
a1

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [61]:
10+a1

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [63]:
a1/0

C:\Users\ADMIN-~1\AppData\Local\Temp/ipykernel_2600/1504525615.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a1/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [64]:
a1**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [65]:
pow(a1,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [66]:
a1 

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [68]:
b = np.array([2,3,1,2,3,2])

In [69]:
b

array([2, 3, 1, 2, 3, 2])

In [70]:
a1+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [71]:
b.T

array([2, 3, 1, 2, 3, 2])

In [73]:
a1

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [72]:
a1+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [74]:
b = b.reshape(1,-1)

In [76]:
b.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [77]:
b1 = b.T

In [78]:
b1

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [79]:
a1+b1

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [80]:
b

array([[2, 3, 1, 2, 3, 2]])

In [81]:
a1

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [82]:
np.sqrt(a1)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [83]:
np.exp(a1)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [84]:
np.log10(a)

C:\Users\ADMIN-~1\AppData\Local\Temp/ipykernel_2600/547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([[      -inf, 0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126]])

In [85]:
x = np.array([1,2,3])

In [86]:
y = x   # Solo copy

In [87]:
y

array([1, 2, 3])

In [88]:
z = np.copy(x)  # Deep copy

In [89]:
z

array([1, 2, 3])

In [90]:
x[0] = 100

In [91]:
y

array([100,   2,   3])

In [92]:
z

array([1, 2, 3])

In [93]:
id(z)

2046567107824

In [94]:
id(x)

2046567108496

In [95]:
id(y)

2046567108496

In [96]:
id(x[0])

2046567075056

In [97]:
y

array([100,   2,   3])

In [98]:
id(y[0])

2046567075312

In [99]:
id(x[1])

2046567074640

In [100]:
id(y[1])

2046567075440

In [101]:
x

array([100,   2,   3])

In [102]:
id(x[0])

2046567074992

In [103]:
id(y[0])

2046567075504

In [104]:
x = np.array([1,2,3])

In [105]:
y = x

In [ ]:
# x & y id are same but their element id should be different

In [110]:
id(x)

2046567108304

In [109]:
id(y)

2046567108304

In [111]:
su = np.array([567,345])

In [112]:
df = su

In [113]:
id(df)

2046567106384

In [114]:
id(su)

2046567106384

In [115]:
id(su[1])

2046567158480

In [116]:
id(df[1])

2046567158544

In [117]:
id(su[1]) == id(df[1])

True

In [118]:
id(su[0]) == id(df[0])

True

In [119]:
id(su) == id(df)


True

In [120]:
xt = np.array([34,67,89])

In [121]:
id(xt[0]) == id(su[0])

True

In [122]:
c = "sudh"

In [124]:
id(c) == id(su[0])

False